#!/usr/bin/env python3
"""
Phase 3 — Assemble the full HSDB 36 nt layout.

Combines:
  - N bar_1 sequences (28 nt, one per block, from Phase 2)
  - 16 bar_2 sequences (8 nt, fixed set, from Phase 1)

Each 4×4 block gets a unique bar_1.  Within each block the 16 bar_2
sequences are randomly permuted across the 16 spots, making every
(bar_1, bar_2) pair globally unique.

Combined barcode: bar_1 (28 nt) + bar_2 (8 nt) = 36 nt

Supports any array size via --array-rows / --array-cols:

  118×182  →  python dual_barcode_hierarchical.py
               (uses 118x182 defaults, bar1 from bar1_barcodes_28nt.txt)

  253×363  →  python dual_barcode_hierarchical.py \\
                  --array-rows 253 --array-cols 363 \\
                  --bar1 ../bar1_zipcode/bar1_barcodes_28nt_253x363.txt \\
                  --out-dir ../outputs/253x363

Outputs (in --out-dir):
  - layout_<rows>x<cols>_hsdb.csv  : column-major CSV with all spot assignments
  - barcodes_hsdb_<rows>x<cols>_36nt.txt : one combined 36 nt barcode per line
                                            in row-major order
  - layout_stats.json              : summary statistics
"""

import argparse
import json
import random
import sys
from pathlib import Path
from typing import List, Dict, Optional

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent

# Default input paths (generated by Phases 1 and 2)
DEFAULT_BAR1_FILE = REPO_ROOT / "HSDB" / "bar1_zipcode" / "bar1_barcodes_28nt.txt"
DEFAULT_BAR2_FILE = REPO_ROOT / "HSDB" / "bar2_library" / "spot_barcodes_8nt.txt"
DEFAULT_OUT_DIR = REPO_ROOT / "HSDB" / "outputs"

# Fixed across all array sizes
BLOCK_SIZE = 4
N_SPOT_IDS = 16    # bar_2 repertoire size — always 16 (4×4 spots per block)
BAR1_LEN = 28
BAR2_LEN = 8
COMBINED_LEN = BAR1_LEN + BAR2_LEN  # 36


# --------------------------------------------------------------------------
# I/O helpers
# --------------------------------------------------------------------------

def load_sequences(path: Path, expected_len: Optional[int] = None) -> List[str]:
    seqs = [line.strip().upper() for line in open(path) if line.strip()]
    if not seqs:
        raise ValueError(f"No sequences found in {path}")
    if expected_len is not None:
        wrong = [s for s in seqs if len(s) != expected_len]
        if wrong:
            raise ValueError(
                f"{len(wrong)} sequences in {path} have unexpected length "
                f"(expected {expected_len} nt); first offender: {wrong[0]} ({len(wrong[0])} nt)"
            )
    return seqs


# --------------------------------------------------------------------------
# QC helpers
# --------------------------------------------------------------------------

def hamming(a: str, b: str) -> int:
    return sum(x != y for x, y in zip(a, b))


def min_pairwise_hamming(seqs: List[str]) -> int:
    if len(seqs) < 2:
        return 0
    return min(hamming(a, b) for i, a in enumerate(seqs) for b in seqs[i + 1:])


def g_fraction(seq: str) -> float:
    return seq.count("G") / len(seq)


def gc_fraction(seq: str) -> float:
    return (seq.count("G") + seq.count("C")) / len(seq)


def max_homopolymer(seq: str) -> int:
    if not seq:
        return 0
    max_run = cur = 1
    for i in range(1, len(seq)):
        cur = cur + 1 if seq[i] == seq[i - 1] else 1
        max_run = max(max_run, cur)
    return max_run


# --------------------------------------------------------------------------
# Layout generation
# --------------------------------------------------------------------------

def generate_layout(
    bar1_seqs: List[str],
    bar2_seqs: List[str],
    array_rows: int,
    array_cols: int,
    seed: Optional[int] = 42,
) -> List[Dict]:
    """
    Assign barcodes to all spots in row-major order.

    Returns a list of dicts, one per spot:
      row, col, block_row, block_col, spot_in_block,
      bar_1, bar_2, combined
    """
    rng = random.Random(seed)

    block_rows = (array_rows + BLOCK_SIZE - 1) // BLOCK_SIZE
    block_cols = (array_cols + BLOCK_SIZE - 1) // BLOCK_SIZE
    n_blocks = block_rows * block_cols

    # Pre-validate inputs
    if len(bar1_seqs) < n_blocks:
        raise ValueError(
            f"Need {n_blocks} bar_1 sequences for a {array_rows}×{array_cols} array "
            f"({block_rows}×{block_cols} blocks), got {len(bar1_seqs)}"
        )
    if len(bar2_seqs) < N_SPOT_IDS:
        raise ValueError(
            f"Need {N_SPOT_IDS} bar_2 sequences, got {len(bar2_seqs)}"
        )

    # bar_1 assignment: bar1_seqs[br * block_cols + bc] is the bar_1 for
    # block (br, bc) — the row-major ordering from generate_block_barcodes.py.

    spots = []

    for br in range(block_rows):
        for bc in range(block_cols):
            block_idx = br * block_cols + bc
            bar1 = bar1_seqs[block_idx]

            # Randomly permute bar_2 across the 16 spots in this block
            permuted_bar2 = bar2_seqs[:N_SPOT_IDS].copy()
            rng.shuffle(permuted_bar2)

            spot_in_block = 0
            for di in range(BLOCK_SIZE):
                for dj in range(BLOCK_SIZE):
                    row = br * BLOCK_SIZE + di
                    col = bc * BLOCK_SIZE + dj

                    # Skip spots outside the physical array
                    if row >= array_rows or col >= array_cols:
                        continue

                    bar2 = permuted_bar2[spot_in_block % N_SPOT_IDS]
                    combined = bar1 + bar2

                    spots.append({
                        "row": row,
                        "col": col,
                        "block_row": br,
                        "block_col": bc,
                        "spot_in_block": spot_in_block,
                        "bar_1": bar1,
                        "bar_2": bar2,
                        "combined": combined,
                    })
                    spot_in_block += 1

    return spots


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

def validate_layout(spots: List[Dict]) -> None:
    """Raise ValueError on any layout constraint violation."""
    combined_seen: Dict[str, tuple] = {}
    block_bar1: Dict[tuple, str] = {}
    block_bar2: Dict[tuple, set] = {}

    for s in spots:
        bk = (s["block_row"], s["block_col"])
        comb = s["combined"]
        pos = (s["row"], s["col"])

        # Global uniqueness of combined barcode
        if comb in combined_seen:
            raise ValueError(
                f"Duplicate combined barcode '{comb}' at {pos} and {combined_seen[comb]}"
            )
        combined_seen[comb] = pos

        # Consistent bar_1 within each block
        if bk in block_bar1:
            if block_bar1[bk] != s["bar_1"]:
                raise ValueError(
                    f"Block {bk}: inconsistent bar_1 "
                    f"('{s['bar_1']}' vs '{block_bar1[bk]}')"
                )
        else:
            block_bar1[bk] = s["bar_1"]

        # Unique bar_2 within each block
        if bk not in block_bar2:
            block_bar2[bk] = set()
        if s["bar_2"] in block_bar2[bk]:
            raise ValueError(
                f"Block {bk}: duplicate bar_2 '{s['bar_2']}'"
            )
        block_bar2[bk].add(s["bar_2"])

    print(f"  Validation passed: {len(combined_seen):,} globally unique combined barcodes")


# --------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------

def export_csv(spots: List[Dict], path: Path) -> None:
    """Write full layout CSV in column-major order (matches existing convention)."""
    # Sort column-major: iterate cols first, then rows
    sorted_spots = sorted(spots, key=lambda s: (s["col"], s["row"]))
    with open(path, "w") as fh:
        fh.write("row,col,block_row,block_col,spot_in_block,bar_1,bar_2,combined\n")
        for s in sorted_spots:
            fh.write(
                f"{s['row']},{s['col']},"
                f"{s['block_row']},{s['block_col']},{s['spot_in_block']},"
                f"{s['bar_1']},{s['bar_2']},{s['combined']}\n"
            )


def export_barcode_txt(spots: List[Dict], path: Path) -> None:
    """Write combined barcodes in row-major order, one per line."""
    sorted_spots = sorted(spots, key=lambda s: (s["row"], s["col"]))
    with open(path, "w") as fh:
        for s in sorted_spots:
            fh.write(s["combined"] + "\n")


# --------------------------------------------------------------------------
# Statistics
# --------------------------------------------------------------------------

def compute_stats(
    spots: List[Dict],
    bar1_seqs: List[str],
    bar2_seqs: List[str],
    array_rows: int,
    array_cols: int,
) -> Dict:
    combined = [s["combined"] for s in spots]
    g_vals = [g_fraction(c) for c in combined]
    gc_vals = [gc_fraction(c) for c in combined]
    hp_vals = [max_homopolymer(c) for c in combined]

    block_rows = (array_rows + BLOCK_SIZE - 1) // BLOCK_SIZE
    block_cols = (array_cols + BLOCK_SIZE - 1) // BLOCK_SIZE
    n_blocks = block_rows * block_cols

    # Per-cycle G frequency (synthesis metric)
    per_cycle_g = []
    for pos in range(COMBINED_LEN):
        g_count = sum(1 for c in combined if c[pos] == "G")
        per_cycle_g.append(round(g_count / len(combined), 4))

    return {
        "array_dims": f"{array_rows}x{array_cols}",
        "total_spots": len(spots),
        "block_grid": f"{block_rows}x{block_cols}",
        "n_blocks": n_blocks,
        "bar1_length": BAR1_LEN,
        "bar2_length": BAR2_LEN,
        "combined_length": COMBINED_LEN,
        "n_unique_bar1": len(set(s["bar_1"] for s in spots)),
        "n_unique_bar2": len(set(s["bar_2"] for s in spots)),
        "n_unique_combined": len(set(combined)),
        "min_hamming_bar2": min_pairwise_hamming(bar2_seqs[:N_SPOT_IDS]),
        "g_content_combined": {
            "mean": round(sum(g_vals) / len(g_vals), 4),
            "max": round(max(g_vals), 4),
            "n_above_25pct": sum(1 for g in g_vals if g > 0.25),
        },
        "gc_content_combined": {
            "mean": round(sum(gc_vals) / len(gc_vals), 4),
            "min": round(min(gc_vals), 4),
            "max": round(max(gc_vals), 4),
        },
        "max_homopolymer": int(max(hp_vals)),
        "per_cycle_g_fraction": per_cycle_g,
        "max_per_cycle_g": max(per_cycle_g),
        "n_cycles_g_above_25pct": sum(1 for g in per_cycle_g if g > 0.25),
    }


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--bar1", default=str(DEFAULT_BAR1_FILE),
                    help="Path to bar_1 barcodes file (28 nt, one per line)")
    ap.add_argument("--bar2", default=str(DEFAULT_BAR2_FILE),
                    help="Path to bar_2 barcodes file (8 nt, one per line)")
    ap.add_argument("--array-rows", type=int, default=118,
                    help="Number of spot rows in the physical array (default 118)")
    ap.add_argument("--array-cols", type=int, default=182,
                    help="Number of spot columns in the physical array (default 182)")
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR),
                    help="Output directory")
    ap.add_argument("--seed", type=int, default=42,
                    help="Random seed for bar_2 permutation within blocks")
    args = ap.parse_args()

    array_rows: int = args.array_rows
    array_cols: int = args.array_cols
    block_rows = (array_rows + BLOCK_SIZE - 1) // BLOCK_SIZE
    block_cols = (array_cols + BLOCK_SIZE - 1) // BLOCK_SIZE
    n_blocks = block_rows * block_cols

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Load inputs
    # ------------------------------------------------------------------
    print(f"Loading bar_1 from {args.bar1}...")
    bar1_seqs = load_sequences(Path(args.bar1), expected_len=BAR1_LEN)
    print(f"  {len(bar1_seqs)} bar_1 sequences loaded")

    print(f"Loading bar_2 from {args.bar2}...")
    bar2_seqs = load_sequences(Path(args.bar2), expected_len=BAR2_LEN)
    print(f"  {len(bar2_seqs)} bar_2 sequences loaded")

    if len(bar1_seqs) < n_blocks:
        print(f"ERROR: need {n_blocks} bar_1 sequences for a {array_rows}×{array_cols} array, "
              f"got {len(bar1_seqs)}", file=sys.stderr)
        sys.exit(1)
    if len(bar2_seqs) < N_SPOT_IDS:
        print(f"ERROR: need {N_SPOT_IDS} bar_2 sequences, got {len(bar2_seqs)}", file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------
    # Generate layout
    # ------------------------------------------------------------------
    print(f"\nGenerating layout for {array_rows}×{array_cols} array "
          f"({block_rows}×{block_cols} blocks of {BLOCK_SIZE}×{BLOCK_SIZE})...")
    spots = generate_layout(bar1_seqs, bar2_seqs,
                            array_rows=array_rows, array_cols=array_cols,
                            seed=args.seed)
    print(f"  {len(spots):,} spots assigned")

    # ------------------------------------------------------------------
    # Validate
    # ------------------------------------------------------------------
    print("\nValidating layout...")
    validate_layout(spots)

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------
    print("\nComputing statistics...")
    stats = compute_stats(spots, bar1_seqs, bar2_seqs,
                          array_rows=array_rows, array_cols=array_cols)

    print(f"  Unique bar_1:          {stats['n_unique_bar1']:,}")
    print(f"  Unique bar_2:          {stats['n_unique_bar2']}")
    print(f"  Unique combined:       {stats['n_unique_combined']:,}")
    print(f"  Min Hamming bar_2:     {stats['min_hamming_bar2']}")
    print(f"  G content (combined):  mean={stats['g_content_combined']['mean']:.3f}  "
          f"max={stats['g_content_combined']['max']:.3f}  "
          f">25%: {stats['g_content_combined']['n_above_25pct']}")
    print(f"  Max per-cycle G:       {stats['max_per_cycle_g']:.3f}")
    print(f"  Cycles with G > 25%:   {stats['n_cycles_g_above_25pct']}")
    print(f"  Max homopolymer:       {stats['max_homopolymer']}")

    # ------------------------------------------------------------------
    # Export — filenames include array dimensions to avoid collisions
    # ------------------------------------------------------------------
    tag = f"{array_rows}x{array_cols}"
    csv_path = out_dir / f"layout_{tag}_hsdb.csv"
    txt_path = out_dir / f"barcodes_hsdb_{tag}_36nt.txt"
    stats_path = out_dir / f"layout_stats_{tag}.json"

    export_csv(spots, csv_path)
    print(f"\nWrote layout CSV     → {csv_path}")

    export_barcode_txt(spots, txt_path)
    print(f"Wrote barcodes TXT   → {txt_path}")

    with open(stats_path, "w") as fh:
        json.dump(stats, fh, indent=2)
    print(f"Wrote stats JSON     → {stats_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
